export const SUBMISSION_LIMITS = {
  MAX_WRONG_ATTEMPTS: 8,
  ATTEMPT_WINDOW_SECONDS: 900,
  LOCKOUT_SECONDS: 600,
} as const;
export const SCORE_DECAY = { PER_SOLVE: 0.05, MIN_RATIO: 0.5 } as const;
export const CHALLENGE_RULES = {
  TITLE_MIN: 4,
  TITLE_MAX: 120,
  DESCRIPTION_MIN: 20,
  DESCRIPTION_MAX: 10000,
  POINTS_MIN: 50,
  POINTS_MAX: 1000,
  MAX_HINTS: 5,
} as const;
export const AUTH_RULES = {
  PASSWORD_MIN: 8,
  PASSWORD_MAX_BYTES: 72,
  CODE_TTL_SECONDS: 600,
  CODE_ATTEMPTS: 5,
  RESET_TTL_SECONDS: 900,
} as const;
export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
} as const;
export const UPLOAD_LIMIT_BYTES = 100 * 1024 * 1024;
