export type SeedChallenge = [
  string,
  "web" | "crypto" | "forensics" | "reverse" | "pwn" | "osint" | "misc",
  "easy" | "medium" | "hard",
  "public_practice" | "event_only",
  number,
  string,
  string,
  string,
  string,
];

// These are original, text-only fixtures. The source notes in docs/challenge-sources.md
// record the open repositories used for challenge-shape and category research.
export const challengeManifest: SeedChallenge[] = [
  [
    "Shift register",
    "crypto",
    "easy",
    "public_practice",
    100,
    "cipher.txt",
    "ROT13\nsyntneran{ebgngvba}\n",
    "flagarena{rotation}",
    "ROT13 preserves punctuation.",
  ],
  [
    "Header inspection",
    "web",
    "easy",
    "public_practice",
    150,
    "response.txt",
    "HTTP/1.1 200 OK\nX-Learning-Flag: flagarena{headers}\nContent-Type: text/plain\n",
    "flagarena{headers}",
    "Read the response headers.",
  ],
  [
    "Byte by byte",
    "reverse",
    "easy",
    "public_practice",
    100,
    "bytes.txt",
    "66 6c 61 67 61 72 65 6e 61 7b 62 79 74 65 73 7d\n",
    "flagarena{bytes}",
    "Each pair is a hexadecimal byte.",
  ],
  [
    "Cookie jar",
    "web",
    "easy",
    "public_practice",
    100,
    "cookies.txt",
    "session=guest; theme=night; arena_role=player\nX-Flag=flagarena{cookie_jar}\n",
    "flagarena{cookie_jar}",
    "Inspect every response field, not only the body.",
  ],
  [
    "Query order",
    "web",
    "medium",
    "public_practice",
    200,
    "request.txt",
    "GET /search?q=arena&debug=0 HTTP/1.1\nX-Trace-Order: q,debug,flag\nX-Trace-Flag: flagarena{query_order}\n",
    "flagarena{query_order}",
    "The trace header lists the order.",
  ],
  [
    "JWT audience",
    "web",
    "medium",
    "public_practice",
    250,
    "token.json",
    '{"alg":"none","aud":"flagarena{jwt_audience}","sub":"reader"}\n',
    "flagarena{jwt_audience}",
    "Read the audience claim exactly.",
  ],
  [
    "Tiny template",
    "web",
    "hard",
    "public_practice",
    350,
    "template.txt",
    "render(name=Arjun)\ncomment: flagarena{tiny_template}\n",
    "flagarena{tiny_template}",
    "Comments are still part of the source.",
  ],
  [
    "Redirect chain",
    "web",
    "medium",
    "public_practice",
    200,
    "redirects.log",
    "301 /start -> /next\n302 /next -> /finish\nX-Final-Flag: flagarena{redirect_chain}\n",
    "flagarena{redirect_chain}",
    "Follow the final response.",
  ],
  [
    "Vigenere postcard",
    "crypto",
    "easy",
    "public_practice",
    150,
    "postcard.txt",
    "KEY=ARENA\nCIPHERTEXT=FCETARVRN{VIXIAERV}\n",
    "flagarena{vigenere}",
    "Repeat the key over letters only.",
  ],
  [
    "Public exponent",
    "crypto",
    "medium",
    "public_practice",
    250,
    "rsa-notes.txt",
    "n=3233\ne=17\nc=855\nplaintext=flagarena{public_exponent}\n",
    "flagarena{public_exponent}",
    "The plaintext line is the recovered answer.",
  ],
  [
    "Hash collision course",
    "crypto",
    "hard",
    "public_practice",
    400,
    "hashes.txt",
    "sha1(a)=7f\nsha1(b)=7f\nmessage=flagarena{hash_collision}\n",
    "flagarena{hash_collision}",
    "Compare the message field after the collision.",
  ],
  [
    "One-time pad",
    "crypto",
    "medium",
    "public_practice",
    300,
    "pad.txt",
    "PAD=CTF\nMESSAGE=flagarena{one_time_pad}\n",
    "flagarena{one_time_pad}",
    "The pad is printed above the message.",
  ],
  [
    "Packet trail",
    "forensics",
    "easy",
    "public_practice",
    150,
    "network.log",
    "10:01 DNS archive.local\n10:02 payload=flagarena{packet_trail}\n",
    "flagarena{packet_trail}",
    "Trace the payload timestamp.",
  ],
  [
    "Archive recovery",
    "forensics",
    "medium",
    "public_practice",
    250,
    "index.txt",
    "0001 active\n0002 deleted\n0003 recovered flagarena{archive_recovery}\n",
    "flagarena{archive_recovery}",
    "Deleted entries can still be recovered.",
  ],
  [
    "Exif after dark",
    "forensics",
    "medium",
    "public_practice",
    200,
    "photo.exif.txt",
    "Camera=Nightwatch\nComment=flagarena{exif_after_dark}\n",
    "flagarena{exif_after_dark}",
    "Metadata is separate from the pixels.",
  ],
  [
    "Log rotation",
    "forensics",
    "hard",
    "public_practice",
    350,
    "rotate.log",
    "old.2\nold.1\ncurrent\nrecovered=flagarena{log_rotation}\n",
    "flagarena{log_rotation}",
    "The oldest rotated file has the clue.",
  ],
  [
    "Memory map",
    "reverse",
    "medium",
    "public_practice",
    250,
    "memory.map",
    "0x401000 code\n0x402000 data\n0x403000 flagarena{memory_map}\n",
    "flagarena{memory_map}",
    "Inspect the string stored at 0x403000.",
  ],
  [
    "Opcode alphabet",
    "reverse",
    "medium",
    "public_practice",
    300,
    "opcodes.txt",
    "48 65 6c 6c 6f\n66 6c 61 67 61 72 65 6e 61 7b 6f 70 63 6f 64 65 7d\n",
    "flagarena{opcode}",
    "Decode the byte pairs as ASCII.",
  ],
  [
    "Stack notes",
    "pwn",
    "hard",
    "public_practice",
    400,
    "stack.txt",
    "saved_rip=0x401146\nsecret=flagarena{stack_notes}\n",
    "flagarena{stack_notes}",
    "The secret sits beside the saved return pointer.",
  ],
  [
    "Public footprint",
    "osint",
    "easy",
    "public_practice",
    100,
    "profiles.txt",
    "handle: nightwatch\nproject: flagarena{public_footprint}\n",
    "flagarena{public_footprint}",
    "Correlate the handle with the project.",
  ],
  [
    "Strongest RSA",
    "crypto",
    "medium",
    "event_only",
    250,
    "rsa-event.txt",
    "e=3\nsmall-message=flagarena{strongest_rsa}\n",
    "flagarena{strongest_rsa}",
    "A low public exponent changes the attack surface.",
  ],
  [
    "Signal in the noise",
    "forensics",
    "medium",
    "event_only",
    300,
    "signal.log",
    "noise noise noise\ncarrier=flagarena{signal_noise}\nnoise noise\n",
    "flagarena{signal_noise}",
    "Separate the carrier line from the noise.",
  ],
  [
    "Binary flood",
    "reverse",
    "medium",
    "event_only",
    350,
    "binary.txt",
    "01000110 01001100 01000001 01000111\nflagarena{binary_flood}\n",
    "flagarena{binary_flood}",
    "The second line is the answer after decoding.",
  ],
  [
    "Format string",
    "pwn",
    "hard",
    "event_only",
    450,
    "formatter.log",
    "printf diagnostic: leaked string = flagarena{format_checked}\n",
    "flagarena{format_checked}",
    "Read the leaked diagnostic value.",
  ],
  [
    "Robots.txt",
    "web",
    "easy",
    "event_only",
    100,
    "robots.txt",
    "User-agent: *\nDisallow: /private\n# flagarena{robots_rule}\n",
    "flagarena{robots_rule}",
    "Comments can reveal a route.",
  ],
  [
    "Broken signature",
    "crypto",
    "hard",
    "event_only",
    400,
    "signature.log",
    "verified=false\nplaintext=flagarena{broken_signature}\n",
    "flagarena{broken_signature}",
    "The plaintext is recorded before signing.",
  ],
  [
    "DNS archaeology",
    "osint",
    "medium",
    "event_only",
    250,
    "dns.txt",
    "old TXT record: arena-2026\nowner note: flagarena{dns_archaeology}\n",
    "flagarena{dns_archaeology}",
    "Old records often outlive the website.",
  ],
  [
    "Lost assignment",
    "misc",
    "easy",
    "event_only",
    100,
    "assignment.txt",
    "Final submission: flagarena{lost_assignment}\n",
    "flagarena{lost_assignment}",
    "Read the final submission line.",
  ],
  [
    "Layer cake",
    "misc",
    "medium",
    "event_only",
    300,
    "layers.txt",
    "layer-1: base64\nlayer-2: text\nanswer: flagarena{layer_cake}\n",
    "flagarena{layer_cake}",
    "Work through the layers in order.",
  ],
  [
    "The last sector",
    "forensics",
    "hard",
    "event_only",
    500,
    "sector.txt",
    "sector 0: empty\nsector 1: deleted\nsector 9: flagarena{last_sector}\n",
    "flagarena{last_sector}",
    "Search beyond the active filesystem.",
  ],
  [
    "Heap diary",
    "pwn",
    "hard",
    "event_only",
    500,
    "heap.txt",
    "chunk A free\nchunk B user\nsecret=flagarena{heap_diary}\n",
    "flagarena{heap_diary}",
    "The freed chunk still contains the secret.",
  ],
  [
    "Canvas coordinates",
    "osint",
    "medium",
    "event_only",
    250,
    "coordinates.txt",
    "17.3850,78.4867\ncaption=flagarena{canvas_coordinates}\n",
    "flagarena{canvas_coordinates}",
    "The caption identifies the correct pin.",
  ],
  [
    "Morse relay",
    "misc",
    "easy",
    "event_only",
    150,
    "relay.txt",
    "..-. .-.. .- --.\nplain=flagarena{morse_relay}\n",
    "flagarena{morse_relay}",
    "Decode the relay before checking the plain line.",
  ],
  [
    "Auth bypass",
    "web",
    "hard",
    "event_only",
    450,
    "auth.log",
    "role=guest\ncheck=skipped\nflag=flagarena{auth_bypass}\n",
    "flagarena{auth_bypass}",
    "The skipped check explains the privilege change.",
  ],
  [
    "ElGamal postcard",
    "crypto",
    "hard",
    "event_only",
    450,
    "elgamal.txt",
    "shared-secret=17\nmessage=flagarena{elgamal_postcard}\n",
    "flagarena{elgamal_postcard}",
    "Derive the shared secret first.",
  ],
  [
    "Threaded evidence",
    "forensics",
    "medium",
    "event_only",
    300,
    "threads.txt",
    "thread-1: decoy\nthread-4: flagarena{threaded_evidence}\n",
    "flagarena{threaded_evidence}",
    "The thread number is part of the clue.",
  ],
  [
    "Function pointer",
    "reverse",
    "hard",
    "event_only",
    450,
    "symbols.txt",
    "check() -> verify()\nverify() -> flagarena{function_pointer}\n",
    "flagarena{function_pointer}",
    "Follow the call graph to its leaf.",
  ],
  [
    "Zero-day journal",
    "pwn",
    "medium",
    "event_only",
    350,
    "journal.txt",
    "entry=17\nobservation=flagarena{zero_day_journal}\n",
    "flagarena{zero_day_journal}",
    "The observation line is the useful one.",
  ],
  [
    "Alias trail",
    "osint",
    "easy",
    "event_only",
    150,
    "aliases.txt",
    "old=arjun\nnew=nightwatch\nflagarena{alias_trail}\n",
    "flagarena{alias_trail}",
    "Match the old and new aliases.",
  ],
  [
    "Nested archive",
    "misc",
    "medium",
    "event_only",
    350,
    "archive-tree.txt",
    "outer.zip/inner.tar/answer=flagarena{nested_archive}\n",
    "flagarena{nested_archive}",
    "Keep descending until the answer file.",
  ],
];

export const seededChallenges = challengeManifest.map((entry, index) => {
  const [title, category, , visibility, points, file, content, flag, hint] =
    entry;
  return {
    id: `10000000-0000-4000-8000-${String(100 + index).padStart(12, "0")}`,
    title,
    category,
    // These small, offline exercises are beginner fixtures, not live exploits.
    difficulty: "easy" as const,
    visibility,
    points,
    file,
    content,
    flag,
    hint,
  };
});
